spring:
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: lb://CLIENTSERVICE
          predicates:
            - Path=/clients/**
        - id: service-voiture
          uri: lb://SERVICE-VOITURE
          predicates:
            - Path=/voitures/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8888
logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
